// types.js
export const FETCH_PAGE_DATA = 'FETCH_PAGE_DATA';
export const FETCH_PAGE_DATA_FAILURE = 'FETCH_PAGE_DATA_FAILURE';
export const FETCH_PAGE_DATA_LOADING = 'FETCH_PAGE_DATA_LOADING';

export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';

export const FETCH_POST_DATA = 'FETCH_POST_DATA';
export const FETCH_POST_LOAD = 'FETCH_POST_LOAD';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';

